'use client';

import { Download, RotateCcw } from 'lucide-react';

interface Insights {
  key_topics: string[];
  entities: string[];
  sentiment: string;
  word_count: number;
  sentence_count: number;
  reading_time_minutes: number;
  document_complexity: string;
}

interface SummaryDisplayProps {
  summary: string;
  insights: Insights;
  filename: string;
  onReset: () => void;
}

export default function SummaryDisplay({
  summary,
  insights,
  filename,
  onReset,
}: SummaryDisplayProps) {
  const downloadSummary = () => {
    const content = `
DOCUMENT SUMMARY & INSIGHTS
=============================

File: ${filename}
Generated: ${new Date().toLocaleString()}

SUMMARY
-------
${summary}

KEY INSIGHTS
------------
Topics: ${insights.key_topics.join(', ')}
Entities: ${insights.entities.slice(0, 10).join(', ')}

DOCUMENT ANALYSIS
-----------------
Word Count: ${insights.word_count}
Sentence Count: ${insights.sentence_count}
Reading Time: ${insights.reading_time_minutes} minutes
Sentiment: ${insights.sentiment}
Complexity: ${insights.document_complexity}

=============================
Generated by Document Summarizer (Local Processing)
    `;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `summary-${filename.split('.')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-4xl mx-auto space-y-6">
      {/* Header */}
      <div className="card">
        <div className="card-body">
          <p className="text-sm text-slate-600 mb-2">Processing Complete</p>
          <h2 className="text-3xl font-bold text-slate-900 break-words">{filename}</h2>
          <div className="flex gap-3 mt-4">
            <button
              onClick={downloadSummary}
              className="btn-primary inline-flex items-center gap-2"
            >
              <Download className="w-4 h-4" />
              Download Summary
            </button>
            <button
              onClick={onReset}
              className="btn-secondary inline-flex items-center gap-2"
            >
              <RotateCcw className="w-4 h-4" />
              Process Another
            </button>
          </div>
        </div>
      </div>

      {/* Summary */}
      <div className="card">
        <div className="card-header">
          <h3 className="text-xl font-bold text-slate-900">📝 Summary</h3>
        </div>
        <div className="card-body">
          <p className="text-slate-700 leading-relaxed">{summary}</p>
        </div>
      </div>

      {/* Key Topics */}
      <div className="card">
        <div className="card-header">
          <h3 className="text-xl font-bold text-slate-900">🎯 Key Topics</h3>
        </div>
        <div className="card-body">
          <div className="flex flex-wrap gap-2">
            {insights.key_topics.map((topic, idx) => (
              <span
                key={idx}
                className="badge bg-blue-100 text-blue-800"
              >
                {topic}
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* Entities */}
      <div className="card">
        <div className="card-header">
          <h3 className="text-xl font-bold text-slate-900">🏷️ Entities Mentioned</h3>
        </div>
        <div className="card-body">
          <div className="flex flex-wrap gap-2">
            {insights.entities.slice(0, 10).map((entity, idx) => (
              <span
                key={idx}
                className="badge bg-purple-100 text-purple-800"
              >
                {entity}
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* Document Analysis */}
      <div className="grid md:grid-cols-2 gap-6">
        {/* Stats */}
        <div className="card">
          <div className="card-header">
            <h3 className="text-xl font-bold text-slate-900">📊 Statistics</h3>
          </div>
          <div className="card-body space-y-4">
            <div className="flex justify-between items-center">
              <span className="text-slate-600">Word Count</span>
              <span className="font-semibold text-slate-900">{insights.word_count}</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-slate-600">Sentences</span>
              <span className="font-semibold text-slate-900">{insights.sentence_count}</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-slate-600">Reading Time</span>
              <span className="font-semibold text-slate-900">~{insights.reading_time_minutes} min</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-slate-600">Complexity</span>
              <span className="font-semibold text-slate-900 capitalize">
                {insights.document_complexity}
              </span>
            </div>
          </div>
        </div>

        {/* Sentiment */}
        <div className="card">
          <div className="card-header">
            <h3 className="text-xl font-bold text-slate-900">💭 Sentiment</h3>
          </div>
          <div className="card-body">
            <div className="flex items-center justify-center h-full">
              <div className="text-center">
                <p className="text-sm text-slate-600 mb-2">Overall Tone</p>
                <p className="text-4xl font-bold capitalize">
                  {insights.sentiment === 'positive' && '😊 Positive'}
                  {insights.sentiment === 'negative' && '😞 Negative'}
                  {insights.sentiment === 'neutral' && '😐 Neutral'}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className="text-center text-sm text-slate-500 py-6">
        <p>✓ All processing was done locally on your device</p>
        <p>✓ No data was sent to external servers</p>
      </div>
    </div>
  );
}
