'use client';

import { Download, RotateCcw, CheckCircle, AlertCircle } from 'lucide-react';
import { useState } from 'react';

interface Insights {
  key_topics: string[];
  entities: string[];
  sentiment: string;
  word_count: number;
  sentence_count: number;
  reading_time_minutes: number;
  document_complexity: string;
}

interface SpellCheck {
  misspelled_count: number;
  misspelled_words: string[];
  corrections: Record<string, { suggestion: string; alternatives: string[] }>;
  accuracy_percentage: number;
}

interface SummaryDisplayProps {
  summary: string;
  insights: Insights;
  filename: string;
  spellCheck?: SpellCheck;
  onReset: () => void;
}

export default function SummaryDisplay({
  summary,
  insights,
  filename,
  spellCheck,
  onReset,
}: SummaryDisplayProps) {
  const [showSpellCheck, setShowSpellCheck] = useState(false);

  const downloadSummary = () => {
    const content = `
DOCUMENT SUMMARY & INSIGHTS
=============================

File: ${filename}
Generated: ${new Date().toLocaleString()}

SUMMARY
-------
${summary}

KEY INSIGHTS
------------
Topics: ${insights.key_topics.join(', ')}
Entities: ${insights.entities.slice(0, 10).join(', ')}

DOCUMENT ANALYSIS
-----------------
Word Count: ${insights.word_count}
Sentence Count: ${insights.sentence_count}
Reading Time: ${insights.reading_time_minutes} minutes
Sentiment: ${insights.sentiment}
Complexity: ${insights.document_complexity}

${spellCheck ? `
SPELLING ANALYSIS
-----------------
Accuracy: ${spellCheck.accuracy_percentage}%
Misspelled Words: ${spellCheck.misspelled_count}
${spellCheck.misspelled_words.length > 0 ? `Words: ${spellCheck.misspelled_words.join(', ')}` : 'No spelling errors found!'}
` : ''}

=============================
Generated by Document Summarizer (Local Processing)
    `;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `summary-${filename.split('.')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="w-full max-w-4xl mx-auto space-y-6">
      {/* Header */}
      <div className="card">
        <div className="card-body">
          <p className="text-sm text-slate-600 mb-2">Processing Complete</p>
          <h2 className="text-3xl font-bold text-slate-900 break-words">{filename}</h2>
          <div className="flex gap-3 mt-4 flex-wrap">
            <button
              onClick={downloadSummary}
              className="btn-primary inline-flex items-center gap-2"
            >
              <Download className="w-4 h-4" />
              Download Summary
            </button>
            <button
              onClick={onReset}
              className="btn-secondary inline-flex items-center gap-2"
            >
              <RotateCcw className="w-4 h-4" />
              Process Another
            </button>
            {spellCheck && (
              <button
                onClick={() => setShowSpellCheck(!showSpellCheck)}
                className={`inline-flex items-center gap-2 px-6 py-2 rounded-lg font-medium transition-colors ${
                  spellCheck.misspelled_count === 0
                    ? 'bg-green-100 text-green-800 hover:bg-green-200'
                    : 'bg-yellow-100 text-yellow-800 hover:bg-yellow-200'
                }`}
              >
                {spellCheck.misspelled_count === 0 ? (
                  <>
                    <CheckCircle className="w-4 h-4" />
                    No Spelling Errors
                  </>
                ) : (
                  <>
                    <AlertCircle className="w-4 h-4" />
                    {spellCheck.misspelled_count} Spelling Issues
                  </>
                )}
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Spell Check Results */}
      {spellCheck && showSpellCheck && (
        <div className="card border-l-4 border-blue-500">
          <div className="card-header bg-blue-50">
            <h3 className="text-xl font-bold text-slate-900">✓ Spelling Analysis</h3>
          </div>
          <div className="card-body space-y-4">
            <div className="flex justify-between items-center">
              <span className="text-slate-600">Accuracy Score</span>
              <div className="flex items-center gap-2">
                <div className="w-32 h-2 bg-slate-200 rounded-full overflow-hidden">
                  <div
                    className={`h-full ${
                      spellCheck.accuracy_percentage >= 90
                        ? 'bg-green-500'
                        : spellCheck.accuracy_percentage >= 70
                        ? 'bg-yellow-500'
                        : 'bg-red-500'
                    }`}
                    style={{ width: `${spellCheck.accuracy_percentage}%` }}
                  ></div>
                </div>
                <span className="font-semibold text-slate-900">
                  {spellCheck.accuracy_percentage}%
                </span>
              </div>
            </div>

            {spellCheck.misspelled_count > 0 && (
              <div>
                <h4 className="font-semibold text-slate-900 mb-2">
                  Misspelled Words ({spellCheck.misspelled_count}):
                </h4>
                <div className="space-y-2">
                  {spellCheck.misspelled_words.map((word) => (
                    <div key={word} className="bg-slate-50 p-3 rounded border border-slate-200">
                      <p className="font-mono font-semibold text-red-600">{word}</p>
                      <p className="text-sm text-slate-600 mt-1">
                        Suggestion:{' '}
                        <span className="font-semibold text-green-600">
                          {spellCheck.corrections[word]?.suggestion}
                        </span>
                      </p>
                      {spellCheck.corrections[word]?.alternatives?.length > 0 && (
                        <p className="text-xs text-slate-500 mt-1">
                          Alternatives:{' '}
                          {spellCheck.corrections[word].alternatives.join(', ')}
                        </p>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {spellCheck.misspelled_count === 0 && (
              <div className="bg-green-50 border border-green-200 p-4 rounded text-center">
                <p className="text-green-800 font-semibold">
                  ✓ No spelling errors found! Your summary is perfect.
                </p>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Summary */}
      <div className="card">
        <div className="card-header">
          <h3 className="text-xl font-bold text-slate-900">📝 Summary</h3>
        </div>
        <div className="card-body">
          <p className="text-slate-700 leading-relaxed">{summary}</p>
        </div>
      </div>

      {/* Key Topics */}
      <div className="card">
        <div className="card-header">
          <h3 className="text-xl font-bold text-slate-900">🎯 Key Topics</h3>
        </div>
        <div className="card-body">
          <div className="flex flex-wrap gap-2">
            {insights.key_topics.map((topic, idx) => (
              <span key={idx} className="badge bg-blue-100 text-blue-800">
                {topic}
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* Entities */}
      <div className="card">
        <div className="card-header">
          <h3 className="text-xl font-bold text-slate-900">🏷️ Entities Mentioned</h3>
        </div>
        <div className="card-body">
          <div className="flex flex-wrap gap-2">
            {insights.entities.slice(0, 10).map((entity, idx) => (
              <span key={idx} className="badge bg-purple-100 text-purple-800">
                {entity}
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* Document Analysis */}
      <div className="grid md:grid-cols-2 gap-6">
        {/* Stats */}
        <div className="card">
          <div className="card-header">
            <h3 className="text-xl font-bold text-slate-900">📊 Statistics</h3>
          </div>
          <div className="card-body space-y-4">
            <div className="flex justify-between items-center">
              <span className="text-slate-600">Word Count</span>
              <span className="font-semibold text-slate-900">{insights.word_count}</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-slate-600">Sentences</span>
              <span className="font-semibold text-slate-900">{insights.sentence_count}</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-slate-600">Reading Time</span>
              <span className="font-semibold text-slate-900">~{insights.reading_time_minutes} min</span>
            </div>
            <div className="flex justify-between items-center">
              <span className="text-slate-600">Complexity</span>
              <span className="font-semibold text-slate-900 capitalize">
                {insights.document_complexity}
              </span>
            </div>
          </div>
        </div>

        {/* Sentiment */}
        <div className="card">
          <div className="card-header">
            <h3 className="text-xl font-bold text-slate-900">💭 Sentiment</h3>
          </div>
          <div className="card-body">
            <div className="flex items-center justify-center h-full">
              <div className="text-center">
                <p className="text-sm text-slate-600 mb-2">Overall Tone</p>
                <p className="text-4xl font-bold capitalize">
                  {insights.sentiment === 'positive' && '😊 Positive'}
                  {insights.sentiment === 'negative' && '😞 Negative'}
                  {insights.sentiment === 'neutral' && '😐 Neutral'}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <div className="text-center text-sm text-slate-500 py-6">
        <p>✓ All processing was done locally on your device</p>
        <p>✓ No data was sent to external servers</p>
      </div>
    </div>
  );
}
